include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    avoid_field_initializers_in_const_classes: false
    avoid_positional_boolean_parameters: false
    flutter_style_todos:  false
    one_member_abstracts: false
    lines_longer_than_80_chars: false
    prefer_constructors_over_static_methods: false
    public_member_api_docs: false

analyzer:
  exclude:
    - lib/**.g.dart
    - lib/**/generated/**
  plugins:
    - custom_lint
